version: '3.8'

services:
  nginx:
    image: nginx:1.27.5-alpine
    container_name: ff-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - ff-network

  db:
    image: mysql:8.0.46
    container_name: ff-mysql
    restart: always
    environment:
      MYSQL_DATABASE: feature_flags_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ff-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.8
    container_name: ff-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - ff-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.8
    container_name: ff-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_BASEPATH=/logs
      - SERVER_REWRITEBASEPATH=true
    depends_on:
      - elasticsearch
    networks:
      - ff-network

  grafana:
    image: grafana/grafana:12.4.3
    container_name: ff-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost/metrics/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - ff-network

  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: prometheus-1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ff-network
  
  redis:
    image: redis:7.4.9-alpine
    container_name: ff-redis
    networks:
      - ff-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ff-nestjs
    volumes:
      - .:/app
      - /app/node_modules      
    depends_on:
      - db
      - elasticsearch
      - redis
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root_password
      DB_DATABASE: feature_flags_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_NODE: http://elasticsearch:9200
    networks:
      - ff-network

networks:
  ff-network:
    driver: bridge

volumes:
  mysql_data:
  es_data:
  grafana_data: