events { worker_connections 1024; }

http {
    upstream nestjs_app {   
        server app:3001;
    }

    server {
        listen 80;

        # Rota para a sua API de Feature Flags
        location /api/ {
            proxy_pass http://nestjs_app/;
            proxy_set_header Host $host;
        }

        # Rota para o Dashboard do Kibana (Auditoria)
        location /logs/ {
            proxy_pass http://ff-kibana:5601/;
        }

        # Rota para o Grafana (Métricas)
        location /metrics/ {
            proxy_pass http://ff-grafana:3000/;
        }
    }
}
