events { worker_connections 1024; }

http {
    upstream nestjs_app {   
        server app:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nestjs_app/;
            proxy_set_header Host $host;
        }

        location /api/ {
            proxy_pass http://nestjs_app/;
            proxy_set_header Host $host;
        }

        location /logs/ {
            proxy_pass http://ff-kibana:5601;
            proxy_set_header kbn-xsrf true;
            proxy_set_header Host $host;
        }

        location /metrics/ {
            proxy_pass http://ff-grafana:3000/;
        }
    }
}
